before_script:
  - GRADLE_USER_HOME=$(pwd)/.gradle
  - export GRADLE_USER_HOME

stages:
  - test

tests:
  stage: test
  image: mcr.microsoft.com/playwright/java:v1.41.0-jammy
  services:
    - name: docker:dind
      command: [ "--tls=false" ]
  variables:
    DOCKER_HOST: "tcp://docker:2375"
    DOCKER_TLS_CERTDIR: ""
    DOCKER_DRIVER: overlay2
    TESTCONTAINERS_HOST_OVERRIDE: "host.docker.internal"

  script:
    - ./gradlew test
